export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const GOOGLE_SIGN_IN = 'GOOGLE_SIGN_IN';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const SET_MODAL = 'SET_MODAL';
export const SET_CHECKOUT_MODAL = 'SET_CHECKOUT_MODAL';
export const SET_LOGINED = 'SET_LOGINED';
export const FETCH_CAROUSEL_DATA = 'FETCH_CAROUSEL_DATA';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SET_ACTIVE_PRODUCT = 'SET_ACTIVE_PRODUCT';
export const SET_PRODUCT_FETCHING = 'SET_PRODUCT_FETCHING';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_COUNT = 'CHANGE_COUNT';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const ADD_CHECKOUT_DATA = 'ADD_CHECKOUT_DATA';
export const DELETE_CHECKOUT_DATA = 'DELETE_CHECKOUT_DATA';
export const SET_ITEM_TO_CHANGE = 'SET_ITEM_TO_CHANGE';
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';